# the name for your notes website
name: Jithendra's Notes

# the description of the notes website
description: Precis is a minimal note taking web-app built over Github Pages. This website itself is built using Precis. Look at the notes below to learn about it.