# the name for your notes website
name: Jithendra's Notes

# the description of the notes website
description: A raw collection of my notes, seamlessly synced with my OBSIDIAN vault, capturing my ongoing explorations and personal learning across various domains, continuously updated as part of my knowledge base.